### ISSUE TITLE
size and scale

### ISSUE THREAD

**Issue by fitnr** [ChicagoCityscape/moatp#1]
Is it more important for all the maps to be at the same scale, or to be the same size? This isn't an issue if all of the 'place' geographies are roughly same dimensions, but if there are one or two outliers there may need to be special rules.

**Comment by stevevance** [comment]
I think it's more important for them to be the same scale, within their "types" (ward, ZIP, community area) and across types. 

The size will come into play when the images are `<img` embedded in a webpage, and will be most likely be automatically shrunk to fit a specific placeholder `div` using CSS. 

The Enterprise Zones are massive, though, relative to the other places. [Here's EZ3](http://www.chicagocityscape.com/places.php?place=enterprisezone-3). Rivers also have awkward shapes. 

<img width="867" alt="screenshot 2016-03-02 14 46 24" src="https://cloud.githubusercontent.com/assets/1330459/13474855/8b48fbba-e085-11e5-834c-6c283f1a11ff.png">

**Comment by fitnr** [comment]
OK, great - are there types beyond
- ward
- ZIP
- community area
- EZ

**Comment by stevevance** [comment]
Yes. There are these types in all:
- community area
- neighborhood
- ward
- Special Service Area (SSA)
- Landmark district
- National Register 
- "Custom"
- CTA station - these would appear as radius/circles around the station
- Metra station
- TIF district
- Member-drawn places
- Industrial corridor
- Enterprise Zone
- Planned Manufacturing District
- ZIP
- Township
- River
- Police district
- Police beat
- County commissioner district
- McPier taxing districts
- Neighborhood organization
- Business organization

**Comment by fitnr** [comment]
Can you post the database schema?

**Comment by stevevance** [comment]
What are you looking for?

**Comment by fitnr** [comment]
Are all the geographies in one table? If so, which column differentiates them. 
If they're in different tables, what are the tables called?

**Comment by stevevance** [comment]
They are all in different tables. 
I emailed you an array of the table names.

**Comment by fitnr** [comment]
I'm not seeing it, can you try neilbfreeman@gmail.com (I'm having some connectivity problems with my site)

**Comment by stevevance** [comment]
sent again

**Comment by fitnr** [comment]
:+1:
