### ISSUE TITLE
Expand parks to include more leisure-like spaces

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#10]
![communityarea-hyde-park](https://cloud.githubusercontent.com/assets/1330459/13767802/ac19ebea-ea3c-11e5-93a3-b4c9c81f7a7f.png)
I thought this empty space in the Hyde Park community area was parking garages, which is why the code was changed to include `amenity` (and `amenity=parking`). But upon better inspection, this area is a sports field tagged `landuse=recreation_ground`. 

Some of the other empty spaces around here are `landuse=grass` and `landuse=construction`. 

@fitnr Can you build in `landuse=recreation_ground` and `landuse=grass` into the `parks` layer but add `landuse` to the amenity fields?

Actually, this brings me to a good point: How can I manage the "Cityscape" version of the repo, while you manage the "generic" version of the repo? Can I update this repo to the latest version of yours and then make pull requests to yours?

**Comment by stevevance** [comment]
I've started updating my version of the repo to include this information. Based on my understanding of how GitHub works, I will have to do pull requests from your fork when you make important changes.

**Comment by fitnr** [comment]
Yes, that sounds right. It should work becuase all of the custom information lives in `config.ini`, which isn't in source control.

**Comment by fitnr** [comment]
> Can you build in landuse=recreation_ground and landuse=grass into the parks layer but add landuse to the amenity fields?

The data in the `landuse` tag will stay in `landuse`, same for `amenity` data. This makes is possible to address geometries with both tags in css: `.landuse_recreation_ground.amenity_parking` styles parking lots that are also recreation grounds (if any).

**Comment by stevevance** [comment]
@fitnr I think I phrased my question in a dumb way about the amenity tags.
