### ISSUE TITLE
"get bounds" in bbox.mk doesn't seem to work

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#12]
The README says to run `make -f bbox.mk` to get a bounding box of all tables in the database. 
I got an error:

```
svgis bounds --latlon bbox/bbox.shp | replace ' ' ,
bash: replace: command not found
make: *** [all] Error 127
```

A bunch of shapefiles were creating in `/bbox`, including a final `bbox.shp`, but no bounding information was echoed.

**Comment by fitnr** [comment]
You don't actually need to run that, since I already calculated the bounding box. I figured I would just save the method for a future date.

The problem here is that `replace` is missing from your system. I can swap it out for another command. Is this on CentOS, Ubuntu or OS X?

**Comment by fitnr** [comment]
Fixed by https://github.com/fitnr/moatp/commit/f1cc7c425fed6f49a0a5bbc102328e51e159f685

**Comment by stevevance** [comment]
It was not on CentOS. I was running this command for the sake of understanding the importance of mentioning it in the README.
