### ISSUE TITLE
Expand the buffer for small Places

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#13]
When a very small Place is mapped, and it's in a less populated part of the city, it lacks a lot of context. See the TIF District 72nd/Cicero here. 
![tif-72nd-cicero](https://cloud.githubusercontent.com/assets/1330459/13782622/df5c28d4-ea95-11e5-9ea2-1e7a9095a498.png)
Because there are no street labels, it's impossible to tell where this is. 

Is it possible to use an expression like this?

```
CASE WHEN ST_Area(geom) < "a quarter square mile" THEN ST_Buffer(geom, 2400) ELSE ST_Buffer(geom, 1200)
```

**Comment by fitnr** [comment]
We can't do that kind of logic within SVGIS, but we could do it in bash somehow:

```
svgis bounds in.shp |
something-something |
xargs svgis draw ... --bounds
```

The "something-something" step might have to be a custom script.
Your data is projected and it's simple arithmetic, but a general solution would need to know the projection. I don't know of tool that does this kind of math on bounding boxes, but it would be trivial to write.

I'm not sure if this is the best approach, let me think on it.

**Comment by fitnr** [comment]
The other way around this would be to add labelling, which unfortunately is a pretty complex problem.
