### ISSUE TITLE
Allow one-place-at-a-time creation

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#17]
MOATP is designed to create maps for all of the Places of a single type in one go. Once those are created, though, it's impossible to create a single new Place of that type without deleting every supporting file for that Place type (like names, shapefile of every Place within that type). 

I'm thinking a solution is to trigger a reset before any individual Place's map is called to be made; the reset would delete the necessary files first. 

This is the command that I can't do without deleting supporting files first:

```
make png/b_business_organizations/businessorganization-north-river-commission.png
```

**Comment by fitnr** [comment]
What supporting files are you worried about deleting? Most of the files pertain only to one place, so deleting them shouldn't be a problem.

Make has a built-in way to build from the a particular place in the chain, and it has a cool name:

```
make --what-if=bar.svg foo.png
```

This will assume that `foo.png` is "infinitely new." So any files farther down the chain will get remade.

A more specific example. This will recreate this place map, assuming that the type shapefile is brand new: 

```
make png/b_township_neighborhoods/township-lake-321.png \
    --what-if shp/b_township_neighborhoods.shp
```

A slightly differerent example. If the townships changed in PSQL, you could do this:

```
rm shp/b_township_neighborhoods.shp
make png/b_township_neighborhoods/township-lake-321.png
```

The next time you want to generate a township map, it will start from `shp/b_township_neighborhoods.shp`.

**Comment by stevevance** [comment]
I'm not worried about deleting files. I _want_ the script to delete the files so that I don't have to delete them myself.

**Comment by fitnr** [comment]
I think the `--what-if` option is exactly what you need. That's the built in way of doing this with make.

**Comment by stevevance** [comment]
This almost worked:

```
make png/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.png \
--what-if=shp/b_neighborhoodgroups.shp \
--what-if=names/b_neighborhoodgroups.csv
```

I'm getting this error:

```
ogr2ogr shp/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.shp shp/b_neighborhoodgroups.shp -f 'ESRI Shapefile' -lco ENCODING=UTF-8 -overwrite -skipfailures -t_srs EPSG:3435 \
    -where "slug='neighborhoodorganization-horner-park-west-neighborhood-association'"
svgis draw -o svg/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.svg bg/multipolygons/parks.shp bg/multipolygons/water.shp bg/multipolygons/buildings.shp bg/lines/roads.shp bg/lines/transit.shp bg/points/stops.shp shp/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.shp --no-viewbox --inline --clip --crs file --scale 2 --padding 1200 --precision 0 --simplify 90 --class-fields highway,railway,amenity,landuse --style style.css --bounds $(svgis bounds shp/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.shp)
ignoring invalid bounds: (0.0, 0.0, 0.0, 0.0)
Drawing has infinite bounds, consider changing projection or bounding box.
convert -density 150 mask/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.svg -negate mask/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.png
convert: pixel cache allocation failed `mask/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.svg' @ error/cache.c/OpenPixelCache/3569.
convert: no images defined `mask/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.png' @ error/convert.c/ConvertImageCommand/3241.
make: *** [mask/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.png] Error 1
```

I don't know why, but a `bbox` file for the `b_neighborhoodgroups` layer was never created.

**Comment by fitnr** [comment]
What happens if you open up `shp/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.shp` in your favorite GIS? The all zero bounds looks like the data is missing.

**Comment by stevevance** [comment]
@fitnr That file is never created. There are `cpg`, `dbf`, `prj`, and `shx`, but those files are all empty (except for PRJ, which has the projection written there).

**Comment by fitnr** [comment]
The `horner-park-west` nbhd association isn't in the `shp/b_neighborhoodgroups.shp`, because the PG database was updated. So this command is generating an empty file:

```
ogr2ogr shp/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.shp shp/b_neighborhoodgroups.shp
    -f 'ESRI Shapefile' -lco ENCODING=UTF-8 -overwrite -skipfailures -t_srs EPSG:3435
    -where "slug='neighborhoodorganization-horner-park-west-neighborhood-association'"
```

If you run`make --always-make png/b_neighborhoodgroups/neighborhoodorganization-horner-park-west-neighborhood-association.png` will create the PNG file. The `--always-make` will force all the files upstream from the PNG to be made.

Going forward, there are two ways to go about this. First, you keep careful track of what geographies have been added, and run the files with `--always-make`. The other is to set up a cron job that remakes everything regularly.

**Comment by stevevance** [comment]
that's a great tip, thank you. 

I tried the latest command in your comment (with the `--always-make`) and I encountered two new problems stemming from this:
1. Running `--always-make` it downloaded new `.osm` files (great, I need updated data), but it ran into a rate-limiting error and aborted downloading new `.osm` files. I don't suppose you can do anything about this?

```
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.
Error: runtime error: open64: 0 Success /osm3s_v0.7.53_osm_base Dispatcher_Client::request_read_and_idx::rate_limited. Please check /api/status for the quota of your IP address. 
```
1. A Python library is having problems. After getting all the pre-requisite files replaced and made, I am trying to make the final PNG file: 

```
make png/b_neighborhoodgroups/neighborhoodorganization-jefferson-park-forward.png
```

It aborts almost immediately with this error message:

```
Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 285.
make: *** [svg/b_neighborhoodgroups/neighborhoodorganization-jefferson-park-forward.svg] Abort trap: 6
```

Then, MacOS says that the `libgeos-3.5.0.dylib` plug-in has crashed, and would I like to report the error and "reopen" it. 

What do you think is happening?

I never updated Xcode after updating to Mac OS Sierra, so I'm going to try that.

**Comment by fitnr** [comment]
The `what-if` option, described in my earlier answer, will run the assuming the argument is new. So: 
`make foo.png --what-if xyz.osm`

I'm not sure about the GEOS error. I haven't updated to Sierra yet, it could be an incompatibility between GEOS and Sierra.

**Comment by stevevance** [comment]
I updated Xcode and the command line tools, and the problem persists. So in the meantime I'll have to run this on a different machine.

**Comment by fitnr** [comment]
I would also try reinstalling GEOS and GDAL

**Comment by stevevance** [comment]
I've reinstalled GDAL v2.1 "complete" from [KyngChaos](http://www.kyngchaos.com/software:frameworks), and I've got GEOS 3.6.1 now, on macOS Sierra 10.12.3. I also updated `numpy` to 1.12 and `svgis` to 0.4.2.

The problem is the same although the line number in `AbstractSTRtree.cpp` has changed to 287. 

- I started from an empty directory, and installed MOATP from this repo. 
- I run `make customboundaries` and the `shp/customboundaries.shp` file is created, and it looks correct in QGIS.

**Comment by stevevance** [comment]
After updating a bunch of things I get a different error, one that seems more primitive because it's referencing a file I don't have installed. 

````
make customboundaries
sed 's,^,png/,;s,$,.png,' slug/customboundaries.csv | xargs /Applications/Xcode.app/Contents/Developer/usr/bin/make
mkdir -p svg/customboundaries
mkdir -p mask/customboundaries
ogr2ogr -f CSV names/customboundaries.csv shp/customboundaries.shp -select slug,name
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.9.dylib
  Referenced from: /usr/local/bin/ogr2ogr
  Reason: image not found
make[1]: *** [names/customboundaries.csv] Abort trap: 6
make: *** [customboundaries] Error 1
````

`ogr2ogr` is looking for `/usr/local/opt/proj/lib/libproj.9.dylib` but I have the file `/usr/local/opt/proj/lib/libproj.12.dylib` instead.

**Comment by stevevance** [comment]
I hope this wasn't a problem we've already dealt with, but I've long had issues with installing new Python packages through `pip` because I didn't have the correct permissions. 

I changed the permissions to my user with `chown -R username /Library/Python/2.7/site-packages` and now map images are being created!

**Comment by fitnr** [comment]
Yikes, don't change those permissions, that's a big security problem! Either install packages with `sudo pip install foo` or `pip install --user foo`. The former will ask for a password then install globally, the latter will install locally in your user directory.

**Comment by stevevance** [comment]
@fitnr I've already changed permissions. How can I change them back?

Adding `sudo` has never been 100% successful (it seems to depend on the package and what it wants to do). I can try doing the latter.

**Comment by fitnr** [comment]
First I would run Disk Utility, which might correct it automatically.  If it doesn't: `sudo chown -R root site-packages`. In general, use the `--user` argument with `pip`, unless you really trust the source software.
