### ISSUE TITLE
How do I grab the "name" from the names.csv in order to add text to the image?

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#19]
I am trying to add the Place name as overlay text on the map image. 

so far I can make it print the Place `slug` on the image, and append the Chicago Cityscape logo. 

````
convert -density $(DENSITY) $< -mask $(filter mask/%,$^) \
-modulate $(MODULATE) +mask $(CONVERTFLAGS) \
-gravity South -pointsize 50 -fill white -annotate +0+15 '$(basename $(@F))' logo.png \
-gravity center -append $@
````
Which produces this image:
![ward-2](https://cloud.githubusercontent.com/assets/1330459/22915051/2368c562-f23a-11e6-9475-f4bd49053110.png)

I grabbed `$(basename $(@F))` from the part of the Make script that creates the shapefiles, and that's what overlays the "slug" text. 

(I'm also looking for a way to adjust the text size relative the final width of the image.)

**Comment by stevevance** [comment]
I can successfully extract the Alderman of a Ward, from the `names/b_wards_2015.csv` file using the command ` grep ward-13 names/b_wards_2015.csv | csvcut -c 2`, but I can't insert that resulting name into the ImageMagick command that adds a label on the image. 

Both of my fake commands output the image properly but both of them have blank `''` name outputs (between `+0+10` and `logo.png`.

**1st fake**
````
name=$(grep $(basename $(@F)) names/$(*D).csv | csvcut -c 2) | \
convert -density $(DENSITY) $< -mask $(filter mask/%,$^) -modulate $(MODULATE) +mask \
$(CONVERTFLAGS) -gravity South -pointsize 40 -fill white \
-annotate +0+10 '$(echo "$name")' \
logo.png -gravity center -append $@
````

Right now `name=$(grep $(basename $(@F)) names/$(*D).csv | csvcut -c 2)` is invalid. 

**2nd fake**
````
convert -density $(DENSITY) $< -mask $(filter mask/%,$^) -modulate $(MODULATE) \
+mask $(CONVERTFLAGS) -gravity South -pointsize 40 -fill white \
-annotate +0+10 '$(grep $(basename $(@F)) names/$(*D).csv | csvcut -c 2)' logo.png \
-gravity center -append $@
````

**Comment by stevevance** [comment]
I did it thanks to Zac Flemig at @chihacknight:
````
convert -density $(DENSITY) $< -mask $(filter mask/%,$^) -modulate $(MODULATE) \
		+mask $(CONVERTFLAGS) -gravity South -pointsize 40 -fill white \
		-annotate +0+10 '$(shell grep -w $(basename $(@F)) names/$(*D).csv | csvcut -c 2 | sed -e s/\"//g)' logo.png \
		-gravity center -append $@
````
All that was missing was `shell` before `grep`. I also added the `sed` command after `csvcut` to get rid of the quotation marks in the CSV.

**Comment by fitnr** [comment]
I would adjust the shell command a bit:
```make
$(shell grep -w $(basename $(@F)) names/$(*D).csv | cut -d , -f 2 | head -n 1)
```
This uses the builtin command `cut`, which should work fine as long as none of the names contain commas. Then `head` limits this to one result, just in case the names file is somehow corrupt and has a double.

**Comment by stevevance** [comment]
@fitnr The Ward names have commas. They are quoted, of course.

**Comment by fitnr** [comment]
ok, then what you have should work well.
