### ISSUE TITLE
map style

### ISSUE THREAD

**Issue by fitnr** [ChicagoCityscape/moatp#2]
I'm interested in is both what layers you would like to see on the map, and how visually prominent each one should be. It would be great to see a sketch of what you imagine one of the maps will look like (an actual sketch on paper, or something digital). If that's not right, just a list of all the layers would suffice.

**Comment by stevevance** [comment]
Layers:
- buildings
- water
- parks
- roads: highway=primary, highway=secondary, and highway=motorway
- the Place boundary

The roads add context in place of having text labels to name the Place. 

I sketched it in QGIS (below). If it's possible to make objects outside of the Place boundary show slightly transparent, that would be a plus. I'm not wed to this color scheme. In fact, it might even look good grayscale or sepia. 

<img width="972" alt="screenshot 2016-03-02 14 50 58" src="https://cloud.githubusercontent.com/assets/1330459/13475020/3ff86c3a-e086-11e5-89e0-212da980639f.png">

<img width="972" alt="screenshot 2016-03-02 14 50 58" src="https://cloud.githubusercontent.com/assets/1330459/13475079/7c557f4c-e086-11e5-9f69-20dd8c5d0a8e.png">

**Comment by fitnr** [comment]
Sadly, it's not currently possible in SVGIS to add opacity effects outside of a feature. It might be reasonable to clip the geometry with ogr2ogr and draw the OSM layers in two pieces, once solid, and once faded.

Otherwise, this looks good, thanks
