### ISSUE TITLE
Rename `*.ql` and `*.txt` files to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [ChicagoCityscape/moatp#20]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@stevevance Would a pull request be accepted?

**Comment by fitnr** [comment]
While not the owner, I think a that PR would have a high probability of being accepted. (@stevevance the TLDR here is that if more repos use this file extension, Github will support syntax highlighting. So a small change here will help other OSM data users)

**Comment by FloEdelmann** [comment]
@stevevance @fitnr I created a PR: #21

**Comment by stevevance** [comment]
thank you for bringing this to my attention! And I'm sorry that I didn't see it earlier. Hi @fitnr Neil

**Comment by FloEdelmann** [comment]
No worries. Thanks for merging!
