### ISSUE TITLE
Invalid slugs

### ISSUE THREAD

**Issue by fitnr** [ChicagoCityscape/moatp#3]
I'd like to use the slug field to name to the files - it's descriptive and should be unique. Except I've found a few small issues:

Duplicate slugs:

```
metrastation-lake-forest
metrastation-western-avenue
metrastation-prairie-crossing-libertyville
```

Slugs with spaces (26 of these):

```
township-hyde park-*
```

Slug with a slash:

```
ctastation-washington/dearborn
```

Slug with a comma:

```
landmarkdistrict-washington-square-extension,-iii
```

(This one technically isn't a problem, but it does require an extra rule to escape)

**Comment by stevevance** [comment]
These should never have happened :)
I will fix them on Saturday.

**Comment by stevevance** [comment]
all are fixed

**Comment by fitnr** [comment]
found some more in `b_township_neighborhoods`:

```
township-rogers park-60
township-rogers park-32
township-rogers park-21
township-rogers park-10
township-rogers park-23
township-rogers park-22
township-rogers park-31
township-rogers park-33
township-rogers park-40
```

**Comment by stevevance** [comment]
fixed
