### ISSUE TITLE
Mixed geometries in some tables

### ISSUE THREAD

**Issue by fitnr** [ChicagoCityscape/moatp#4]
Two tables that mostly contain polygons/multipolygons, but also have a couple of linestring geometries thrown in.

Right now they will be ignored. If they should be included, the best way would be to replace the linestring geometries with polygons.
# users_boundaries

![screen shot 2016-03-08 at 3 23 29 pm](https://cloud.githubusercontent.com/assets/714125/13615138/d8a60cb6-e541-11e5-9efd-058a536fbc83.png)
# customboundaries

![screen shot 2016-03-08 at 3 23 17 pm](https://cloud.githubusercontent.com/assets/714125/13615139/d8b29ef4-e541-11e5-8584-59f252f37566.png)

**Comment by stevevance** [comment]
Are you saying the the whole table will be ignored, or that one of the geometry types in that table will be ignored?

**Comment by fitnr** [comment]
Just the lines are ignored
