### ISSUE TITLE
What operating system?

### ISSUE THREAD

**Issue by fitnr** [ChicagoCityscape/moatp#5]
I'm going to set this up with a command to automatically install the prerequisites. What operating system will you run it on? If Linux, which distro?

**Comment by stevevance** [comment]
I would probably run it on my Mac. 
Otherwise I would probably run it on a Digital Ocean droplet (so it can run without my involvement) using Ubuntu 14+

**Comment by fitnr** [comment]
OK, I'll add install tasks for those platforms.

It's going to take a while to build everything, so running remotely will probably work best.
