### ISSUE TITLE
Add parking garages

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#7]
Near the University of Chicago hospitals in the Hyde Park community area, massive areas are unmapped because they're parking garages. 

Add this to the `queries/buildings.txt` query file before downloading OSMs. 

```
way["amenity"="parking"]["parking"="multi-storey"]({{bbox}});
```

This means they'll be styled the same. 

@fitnr How do I style them differently?

**Comment by fitnr** [comment]
Add `amenity` to `CLASSFIELDS` variable in the `Makefile`, then add something like this to the CSS:

```
.amenity_parking {
    fill: lightgray;
}
```

**Comment by stevevance** [comment]
After I've added it to the Makefile, or in the `make` command, at which step is `amenity` pulled from the data? Is it in `make bgs` when converting from OSM to shapefile?

**Comment by fitnr** [comment]
Ah, yes. You'll have to add "amenity" to the attributes that OGR will pull out. Edit `osm.ini`:

```
[multipolygons]
...
attributes=name,type,boundary,building,landuse,leisure,water,waterway,amenity
```

Then it will be grabbed when converting `.osm` to `.shp`.

**Comment by stevevance** [comment]
Gotcha. I've added this to my repo.
