### ISSUE TITLE
How to add labels

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#8]
I'm interested in adding two kinds of labels. 
1. The Place name, as a kind of watermark, in a fixed location in the lower-right corner of the image. 
2. Labels of parks and some streets. 

Do you know how to add either?

**Comment by fitnr** [comment]
Adding the place name can be done with `convert`:

```
convert png/in.png -bordercolor white -gravity south -splice 0x16 -annotate 0 "My Text" out.png
```

All of the options can be added to the `CONVERTFLAGS` variable.

Getting the place name requires an extra step. I've mocked it up in in [a branch in my repo](https://github.com/fitnr/moatp/commit/8e894be5de486d782d8b9cfc9a169fd2192d6925). It will require each table having a field with the same name (e.g `name`).

**Comment by stevevance** [comment]
What font does that look like?

**Comment by stevevance** [comment]
I'm trying it now...
I added a `name` column to the `communityarea` table.

I used this `CONVERTFLAGS` variable:

```
make communityarea CONVERTFLAGS='-bordercolor white -gravity south -splice 0x16 -annotate 0 $(NAME)'
```

The bottom white border appeared, but I go this error: 

```
Fontconfig error: Cannot load default config file
convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1239.
```

It seems ImageMagick doesn't know where to find fonts:

```
convert -list font
Fontconfig error: Cannot load default config file
```

**Comment by fitnr** [comment]
Sorry, I should have linked to the [ImageMagick docs](http://www.imagemagick.org/script/command-line-options.php#annotate). You can specify a file as the text like so:

```
-annotate  0 @file.txt
```

I edited `config.ini` like so:

```
CONVERTFLAGS= -resize 800x\> -gravity south -bordercolor white -splice 0x16 -font "Interstate-Bold" -annotate 0 @$(filter %.csv,$^)
```

(The last part gets the file name from the png's prerequisites)

But, I think you have a font problem. Next comment will address that.

**Comment by fitnr** [comment]
This command should list a bunch of fonts: `convert -list font`

If you get nothing, or an error, then ImageMagick can't find the system's fonts. 
On Linux, the font folder should be at `/etc/fonts`. If it isn't, try `find / -type d -name fonts`. When you have it in hand, run 

```
FONTCONFIG_PATH=/etc/fonts
convert -list font
```

If you get a nice list, then add `export FONTCONFIG_PATH=/etc/fonts` to `.bash_profile`.

**Comment by stevevance** [comment]
I'm doing this on Mac now. I ran:

```
FONTCONFIG_PATH=/Library/Fonts
```

But listing the fonts with convert doesn't have any effect.

**Comment by fitnr** [comment]
Try `brew install ghostscript`

If that doesn't work,

```
brew uninstall imagemagick
brew install imagemagick --with-fontconfig --with-ghostscript
```

**Comment by stevevance** [comment]
It works now! This is so cool!
![communityarea-lincoln-square](https://cloud.githubusercontent.com/assets/1330459/13756951/482ad7b2-e9f0-11e5-858b-1f3fbbba9066.png)

I made the height 0x48 instead of 0x16, and I changed the `-annotate 0` position to `-annotate +0+1`, but it's not in the right position below the map. 

Final command:

```
make communityarea CONVERTFLAGS='-resize 800x\> -gravity south -bordercolor white -splice 0x48 -font "Helvetica" -annotate +0+1 @$(filter %.csv,$^)'
```

**Comment by fitnr** [comment]
The first argument to `-annotate` is an angle, so it should just be 0. You can add another `-splice` argument after the `-annotate` argument.

To answer your other question: It's not currently possible to add text labels with `svgis`. It's something that I might add in the future.

**Comment by stevevance** [comment]
Can you merge `names` into `master` now?

**Comment by fitnr** [comment]
done

**Comment by stevevance** [comment]
It's still not exactly what I want, but it'll do for now:

```
make png/communityarea/communityarea-loop.png CONVERTFLAGS='-resize 800x\> -gravity south -bordercolor white -splice 0x60 -font "Helvetica" -annotate 0 @$(filter %.csv,$^)'
```
