### ISSUE TITLE
CTA stations don't appear in center of the circle

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/moatp#9]
A few of the CTA stations are not appearing in the center of the circle. Cumberland was the first map with this problem, and it's a case of having two different data sources (the dot is placed by OSM data, and the circle's center is placed by Chicago Cityscape Places data). 

I was going to overlook Cumberland but then I saw Belmont (Blue) and it was about a block off. 

Cumberland:
![ctastation-cumberland](https://cloud.githubusercontent.com/assets/1330459/13748522/2454fc84-e9cb-11e5-9d77-49a6c2430417.png)

Belmont (Blue):
![ctastation-belmont-ohare](https://cloud.githubusercontent.com/assets/1330459/13748524/26e541de-e9cb-11e5-9616-eaa4f0f8c667.png)

**Comment by fitnr** [comment]
Same as #6
